---
id: zpnight
base_name: pgroonga-and-zulip
tags:
- rabbit
- zulip
- pgroonga
- postgresql
presentation_date: 2017-09-06
version: 2017.9.6.1
licenses:
- CC-BY-SA-4.0
slideshare_id: zpnight
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: 
